org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.paths=/home/mmlo/.local/jdk/jdk-17.0.20.1+1

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.16.14
loom_version=1.17-SNAPSHOT

mod_version=1.0.6
maven_group=studio.threedonkeys
archives_base_name=world-copies-everything-1.21.11

fabric_api_version=0.139.5+1.21.11
