pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}


rootProject.name = 'world-copies-everything-26-2'



// 26.2 and 26.3 use Loom 1.17 (unobfuscated) and must be built as standalone projects:
//   ./gradlew -p versions/26.2 jar
//   ./gradlew -p versions/26.3 jar
